name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List dist directory
        run: ls -la dist

      - name: Package project
        run: npm run pkg

      - name: List dist directory after pkg
        run: ls -la dist

      - name: Rename and Package Binary
        shell: bash
        run: |
          mkdir -p release
          mv dist/jumper-${{ matrix.arch }} release/jumper
          cd release
          tar -czf ../jumper-${{ matrix.arch }}.tar.gz jumper
          cd ..
          echo "ASSET_PATH=jumper-${{ matrix.arch }}.tar.gz" >> $GITHUB_ENV

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: jumper-${{ matrix.arch }}
          path: jumper-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download x64 release asset
        uses: actions/download-artifact@v4
        with:
          name: jumper-x64
          path: .

      - name: Download arm64 release asset
        uses: actions/download-artifact@v4
        with:
          name: jumper-arm64
          path: .

      - name: Get commit messages
        id: commits
        run: |
          echo "$(git log -1 --pretty=format:%s)" > commit_message.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            ${{ steps.commits.outputs.commit_message }}
          draft: false
          prerelease: false
          files: |
            jumper-x64.tar.gz
            jumper-arm64.tar.gz